/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

/**
 *
 * @author victor
 */
public class DetalhesDeputados extends javax.swing.JFrame {

    /**
     * Creates new form ListaComissao
     */
    public DetalhesDeputados() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelDetalhes = new javax.swing.JPanel();
        jLabelUFRepresentacaoAtual = new javax.swing.JLabel();
        jTextFieldUFRepresentacaoAtual = new javax.swing.JTextField();
        jLabelSituaçaoLegislatura = new javax.swing.JLabel();
        jTextFieldSituacaoLegislatura = new javax.swing.JTextField();
        jLabelDataNascimento = new javax.swing.JLabel();
        jTextFieldDataNascimento = new javax.swing.JTextField();
        jLabelDataFalecimento = new javax.swing.JLabel();
        jTextFieldDataFalecimento = new javax.swing.JTextField();
        jLabelNumeroLegislatura = new javax.swing.JLabel();
        jTextFieldNumeroLegislatura = new javax.swing.JTextField();
        jPanelFoto = new javax.swing.JPanel();
        jLabelFOTO = new javax.swing.JLabel();
        jLabelFoto = new javax.swing.JLabel();
        jButtonFechar = new javax.swing.JButton();
        jLabelFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(740, 500));
        setResizable(false);
        getContentPane().setLayout(null);

        jPanelDetalhes.setMinimumSize(new java.awt.Dimension(0, 0));
        jPanelDetalhes.setName(""); // NOI18N
        jPanelDetalhes.setLayout(null);

        jLabelUFRepresentacaoAtual.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabelUFRepresentacaoAtual.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelUFRepresentacaoAtual.setText("UF de representação atual:");
        jPanelDetalhes.add(jLabelUFRepresentacaoAtual);
        jLabelUFRepresentacaoAtual.setBounds(10, 10, 240, 21);

        jTextFieldUFRepresentacaoAtual.setEditable(false);
        jPanelDetalhes.add(jTextFieldUFRepresentacaoAtual);
        jTextFieldUFRepresentacaoAtual.setBounds(270, 10, 330, 27);

        jLabelSituaçaoLegislatura.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabelSituaçaoLegislatura.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelSituaçaoLegislatura.setText("Situação na legislatura atual:");
        jPanelDetalhes.add(jLabelSituaçaoLegislatura);
        jLabelSituaçaoLegislatura.setBounds(-10, 40, 260, 21);

        jTextFieldSituacaoLegislatura.setEditable(false);
        jPanelDetalhes.add(jTextFieldSituacaoLegislatura);
        jTextFieldSituacaoLegislatura.setBounds(270, 40, 330, 27);

        jLabelDataNascimento.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabelDataNascimento.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelDataNascimento.setText("Data de nascimento:");
        jPanelDetalhes.add(jLabelDataNascimento);
        jLabelDataNascimento.setBounds(10, 70, 240, 21);

        jTextFieldDataNascimento.setEditable(false);
        jPanelDetalhes.add(jTextFieldDataNascimento);
        jTextFieldDataNascimento.setBounds(270, 70, 330, 27);

        jLabelDataFalecimento.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabelDataFalecimento.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelDataFalecimento.setText("Data de falecimento:");
        jPanelDetalhes.add(jLabelDataFalecimento);
        jLabelDataFalecimento.setBounds(10, 100, 240, 21);

        jTextFieldDataFalecimento.setEditable(false);
        jPanelDetalhes.add(jTextFieldDataFalecimento);
        jTextFieldDataFalecimento.setBounds(270, 100, 330, 27);

        jLabelNumeroLegislatura.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabelNumeroLegislatura.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelNumeroLegislatura.setText("Número de legislatura:");
        jPanelDetalhes.add(jLabelNumeroLegislatura);
        jLabelNumeroLegislatura.setBounds(10, 130, 240, 21);

        jTextFieldNumeroLegislatura.setEditable(false);
        jPanelDetalhes.add(jTextFieldNumeroLegislatura);
        jTextFieldNumeroLegislatura.setBounds(270, 130, 330, 27);

        jPanelFoto.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanelFotoLayout = new javax.swing.GroupLayout(jPanelFoto);
        jPanelFoto.setLayout(jPanelFotoLayout);
        jPanelFotoLayout.setHorizontalGroup(
            jPanelFotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelFOTO, javax.swing.GroupLayout.DEFAULT_SIZE, 396, Short.MAX_VALUE)
        );
        jPanelFotoLayout.setVerticalGroup(
            jPanelFotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelFOTO, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
        );

        jPanelDetalhes.add(jPanelFoto);
        jPanelFoto.setBounds(160, 200, 400, 250);

        jLabelFoto.setFont(new java.awt.Font("Ubuntu", 1, 36)); // NOI18N
        jLabelFoto.setText("FOTO");
        jPanelDetalhes.add(jLabelFoto);
        jLabelFoto.setBounds(300, 160, 110, 40);

        jButtonFechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Fechar.png"))); // NOI18N
        jButtonFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFecharActionPerformed(evt);
            }
        });
        jPanelDetalhes.add(jButtonFechar);
        jButtonFechar.setBounds(700, 0, 40, 40);

        jLabelFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/telaDeFundo5.jpg"))); // NOI18N
        jPanelDetalhes.add(jLabelFundo);
        jLabelFundo.setBounds(0, 0, 740, 500);

        getContentPane().add(jPanelDetalhes);
        jPanelDetalhes.setBounds(0, 0, 740, 500);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFecharActionPerformed
        dispose();
    }//GEN-LAST:event_jButtonFecharActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DetalhesDeputados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DetalhesDeputados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DetalhesDeputados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DetalhesDeputados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DetalhesDeputados().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonFechar;
    private javax.swing.JLabel jLabelDataFalecimento;
    private javax.swing.JLabel jLabelDataNascimento;
    private javax.swing.JLabel jLabelFOTO;
    private javax.swing.JLabel jLabelFoto;
    private javax.swing.JLabel jLabelFundo;
    private javax.swing.JLabel jLabelNumeroLegislatura;
    private javax.swing.JLabel jLabelSituaçaoLegislatura;
    private javax.swing.JLabel jLabelUFRepresentacaoAtual;
    private javax.swing.JPanel jPanelDetalhes;
    private javax.swing.JPanel jPanelFoto;
    private javax.swing.JTextField jTextFieldDataFalecimento;
    private javax.swing.JTextField jTextFieldDataNascimento;
    private javax.swing.JTextField jTextFieldNumeroLegislatura;
    private javax.swing.JTextField jTextFieldSituacaoLegislatura;
    private javax.swing.JTextField jTextFieldUFRepresentacaoAtual;
    // End of variables declaration//GEN-END:variables
}
